
version: '3.8'
services:
  
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

app:
    image: paleksey021/devopsapp:latest
    command: >
      sh -c "
      mkdir -p /devops_demo/devops_demo/static &&
      poetry run python /devops_demo/manage.py makemigrations &&
      poetry run python /devops_demo/manage.py migrate &&
      poetry run python /devops_demo/manage.py runserver 0.0.0.0:8000
      poetry run python /devops_demo/manage.py createsuperuser
      "
    depends_on:
      - db
    environment:
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: 127.0.0.1
      DB_PORT: 5432
    ports:
      - "8000:8000"
    volumes:
      - .:/code

volumes:
  postgres_data:
